### ISSUE TITLE
make crashes caused by missing /etc/avahi/aliases

### ISSUE THREAD

**Issue by thoschworks** [piku/avahi-aliases#1]
I tried to install _avahi-aliases_ but `make install` crashed  in line 15, because `/etc/avahi/aliases` has not been created in the installation process (in the [original version](https://github.com/airtonix/avahi-aliases) and the other pip flavored solutions the config files are coppied from the package to the file system).

```
…
>>> Installing systemd unit
sudo cp etc/avahi-alias.service /etc/systemd/system/
sudo systemctl daemon-reload
>>> Enabling systemd unit
sudo systemctl enable avahi-alias.service
Created symlink /etc/systemd/system/multi-user.target.wants/avahi-alias.service → /etc/systemd/system/avahi-alias.service.
sudo systemctl restart avahi-alias.service
Job for avahi-alias.service failed because the control process exited with error code.
See "systemctl status avahi-alias.service" and "journalctl -xe" for details.
make: *** [Makefile:15: install-unit] Fehler 1
```

O.k., let's look what happened:

```
thosch@testbed:~/avahi-aliases-master $ systemctl status avahi-alias.service
● avahi-alias.service - Avahi Aliases
   Loaded: loaded (/etc/systemd/system/avahi-alias.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-05-25 12:18:09 BST; 20s ago
  Process: 2868 ExecStart=/usr/local/bin/avahi-publish-aliases (code=exited, status=1/FAILURE)

Mai 25 12:18:08 testbed systemd[1]: Starting Avahi Aliases...
Mai 25 12:18:09 testbed avahi-publish-aliases[2868]: Traceback (most recent call last):
Mai 25 12:18:09 testbed avahi-publish-aliases[2868]:   File "/usr/local/bin/avahi-publish-aliases", line 19, in <module>
Mai 25 12:18:09 testbed avahi-publish-aliases[2868]:     alias_file = open(alias_file_path)
Mai 25 12:18:09 testbed avahi-publish-aliases[2868]: FileNotFoundError: [Errno 2] No such file or directory: '/etc/avahi/aliases'
Mai 25 12:18:09 testbed systemd[1]: avahi-alias.service: Control process exited, code=exited, status=1/FAILURE
Mai 25 12:18:09 testbed systemd[1]: avahi-alias.service: Failed with result 'exit-code'.
Mai 25 12:18:09 testbed systemd[1]: Failed to start Avahi Aliases.
```

Let's try to add an alias, the file should be generated…

```
thosch@testbed:~/avahi-aliases-master $ avahi-add-alias testhost.local
Traceback (most recent call last):
  File "/usr/local/bin/avahi-add-alias", line 8, in <module>
    alias_file = open("/etc/avahi/aliases")
IOError: [Errno 2] No such file or directory: '/etc/avahi/aliases'
```

Ooops! 😮 

After _manually_ adding `/etc/avahi/aliases` the second run of `make install` worked fine.

**Comment by emaiax** [comment]
@thoschworks my PR fixes this issue. Thank you!

**Comment by thoschworks** [comment]
@emaiax Thanks for fixing this issue. :+1:

It would be nice, if @rcarmo or @piku would merge your PR...

Or I have to switch to your fork.

Edit: fix typo

**Comment by rcarmo** [comment]
Didn’t have notifications for this repo. Will look into that.
